INSERT INTO BAND VALUES(null, 'Borderline',1,'CA');
INSERT INTO BAND VALUES(null, 'Face Value',1,'IL');
INSERT INTO BAND VALUES(null, 'Outspoken',1,'CA');

INSERT INTO BAND VALUES(null, 'Various',6,'unkown');
INSERT INTO BAND VALUES(null, 'Die Hard',1,'IL');
INSERT INTO BAND VALUES(null, 'Blind Spot',1 ,'CA');
INSERT INTO BAND VALUES(null, 'Relapse',1,'MI');
INSERT INTO BAND VALUES(null, 'Endpoint',1,'KY');
INSERT INTO BAND VALUES(null, 'Process',1,'CA');
INSERT INTO BAND VALUES(null, 'Hard Stance',1,'CA');
INSERT INTO BAND VALUES(null, 'Walk Proud',1,'CA');
INSERT INTO BAND VALUES(null, 'Pressure Release',1,'NY');
INSERT INTO BAND VALUES(null, 'Powerhouse',1,'FL');
INSERT INTO BAND VALUES(null, 'Turning Point',1,'NJ');
INSERT INTO BAND VALUES(null, 'Up Front',1,'NY');
INSERT INTO BAND VALUES(null, 'Mouthpiece',1,'NJ');
INSERT INTO BAND VALUES(null, 'Lifetime',2,'NJ');
INSERT INTO BAND VALUES(null, 'Resurection',1,'unkown');
INSERT INTO BAND VALUES(null, 'Strife',3,'CA');


INSERT INTO BAND VALUES(null, 'Mean Season',1,'CA');
INSERT INTO BAND VALUES(null, 'Unbroken',2,'CA');
INSERT INTO BAND VALUES(null, 'Inner Strength',1,'WA');
INSERT INTO BAND VALUES(null, 'Billingsgate',1,'IL');
INSERT INTO BAND VALUES(null, 'Integrity',1,'OH');
INSERT INTO BAND VALUES(null, 'Insight',1,'UT');
INSERT INTO BAND VALUES(null, 'Iceburn',2,'UT');
INSERT INTO BAND VALUES(null, 'Worlds Collide',1,'D.C.');
INSERT INTO BAND VALUES(null, 'Snapcase',2,'NY');
INSERT INTO BAND VALUES(null, 'Warzone',2,'NY');
INSERT INTO BAND VALUES(null, 'Earth Crisis',1,'NY');
INSERT INTO BAND VALUES(null, 'Hifi and the Roadburners',1,'IL');
INSERT INTO BAND VALUES(null, 'Blackout',1,'CA');
INSERT INTO BAND VALUES(null, 'Collateral Damage',1,'CA');
INSERT INTO BAND VALUES(null, 'Dempsey',1,'CA');
INSERT INTO BAND VALUES(null, 'Nineironspitfire',1,'WA');
INSERT INTO BAND VALUES(null, 'Ensign',3,'NJ');
INSERT INTO BAND VALUES(null, 'Eyelid',1,'CA');
INSERT INTO BAND VALUES(null, 'The Dynamic Seven',1,'CA');
INSERT INTO BAND VALUES(null, 'Adamantium',1,'CA');
INSERT INTO BAND VALUES(null, 'The Third Degree',1,'CA');
INSERT INTO BAND VALUES(null, 'Chain of Strength',1,'CA');
INSERT INTO BAND VALUES(null, 'End to End',1,'CA');

INSERT INTO LABEL VALUES (NULL, 'Foundation Records', 'P.O. Box 69386 Los Angeles, CA 90069','818-398-7753','FoundationRec@Gmail.com',2);
INSERT INTO LABEL VALUES (NULL, 'Indescision Records', 'P.O. Box 6052 Garden Grove, CA 92846','657-398-9973','IndescisionRecords@hotmail.com',14);
INSERT INTO LABEL VALUES (NULL, 'Victory Records', '17 Kingery Quater #107 Hinsdale, IL 60521','630-745-9812','VictoryRecords@gmail.com',16);
INSERT INTO LABEL VALUES (NULL, 'New Age Records', 'P.O. Box 3934, Mission Viejo, CA 92690','949-882-6489','NewAgeRecords@yahoo.com',16);
INSERT INTO LABEL VALUES (NULL, 'Conversion Records', '26861 Trabuco Rd., Suite E-143 Mission Viejo, CA 92691','949-109-8143','ConversionRecords@Gmail.com',15);

INSERT INTO ALBUM VALUES(null, 'What Holds Us Apart', 1990, 'EP', 41, 1);
INSERT INTO ALBUM VALUES(null, 'End To End', 1990, 'EP', 42, 1);
INSERT INTO ALBUM VALUES(null, 'Strife', 1992, 'EP', 19, 2);
INSERT INTO ALBUM VALUES(null, 'BeastLab/The Slip Away', 1994, 'EP', 32, 2);
INSERT INTO ALBUM VALUES(null, 'Collateral Damage', 1994, 'EP', 33, 2);
INSERT INTO ALBUM VALUES(null, 'Dempsey', 1995, 'EP', 34, 2);
INSERT INTO ALBUM VALUES(null, 'Guilt By Association', 1995, 'LP', 4, 2);
INSERT INTO ALBUM VALUES(null, 'Seventh Soul Sacrificed', 1996, 'EP', 35, 2);
INSERT INTO ALBUM VALUES(null, 'Ensign', 1996, 'EP', 36, 2);
INSERT INTO ALBUM VALUES(null, 'Fall From Grace', 1997, 'EP', 36, 2);
INSERT INTO ALBUM VALUES(null, 'Direction of Things to Come', 1997, 'LP', 36, 2);
INSERT INTO ALBUM VALUES(null, 'If It Kills', 1998, 'LP', 37, 2);
INSERT INTO ALBUM VALUES(null, 'Filthy Statement', 1998, 'EP', 38, 2);
INSERT INTO ALBUM VALUES(null, 'From The Depths of Depresssion', 1998, 'LP', 39, 2);
INSERT INTO ALBUM VALUES(null, 'Devil''s Night', 1998, 'EP', 4, 2);
INSERT INTO ALBUM VALUES(null, '7-Ply''s / Kill Me', 1998, 'EP', 40, 2);

INSERT INTO ALBUM VALUES(null, 'Time For Reality', 1989, 'EP', 22, 3);
INSERT INTO ALBUM VALUES(null, 'Reach Out', 1990, 'EP', 23, 3);
INSERT INTO ALBUM VALUES(null, 'In Contrast Of Sin', 1990, 'EP', 24, 3);
INSERT INTO ALBUM VALUES(null, 'What Will It Take?', 1990, 'EP', 25, 3);
INSERT INTO ALBUM VALUES(null, 'Only The Strong', 1990, 'EP', 4, 3);
INSERT INTO ALBUM VALUES(null, 'Burn / Fall', 1991, 'EP', 26, 3);
INSERT INTO ALBUM VALUES(null, 'Worlds Collide', 1992, 'EP', 27, 3);
INSERT INTO ALBUM VALUES(null, 'Firon', 1992, 'LP', 26, 3);
INSERT INTO ALBUM VALUES(null, 'Comatose', 1992, 'EP', 28, 3);
INSERT INTO ALBUM VALUES(null, 'Only The Strong', 1993, 'EP', 4, 3);
INSERT INTO ALBUM VALUES(null, 'Live at CBGB', 1993, 'EP', 29, 3);
INSERT INTO ALBUM VALUES(null, 'Firestorm', 1993, 'EP', 30, 3);
INSERT INTO ALBUM VALUES(null, 'Lookingglasself', 1993, 'LP', 28, 3);
INSERT INTO ALBUM VALUES(null, 'Demons Of Wicker Park', 1993, 'EP', 31, 3);
INSERT INTO ALBUM VALUES(null, 'Old School To New School', 1994, 'LP', 29, 3);
INSERT INTO ALBUM VALUES(null, 'One Truth', 1994, 'LP', 19, 3);

INSERT INTO ALBUM VALUES(null, 'Be Yourself', 1988, 'EP', 11, 4);
INSERT INTO ALBUM VALUES(null, 'Prison Of My Own', 1990, 'EP', 23, 4);
INSERT INTO ALBUM VALUES(null, 'Powerhouse', 1990, 'EP', 13, 4);
INSERT INTO ALBUM VALUES(null, 'It''s Always Darkest', 1990, 'LP',14, 4);
INSERT INTO ALBUM VALUES(null, 'Survival', 1990, 'EP', 3, 4);
INSERT INTO ALBUM VALUES(null, 'Daybreak', 1990, 'EP', 15, 4);
INSERT INTO ALBUM VALUES(null, 'Words To Live By Words To Die For', 1991, 'EP', 4, 4);
INSERT INTO ALBUM VALUES(null, 'Mouthpiece', 1991, 'EP', 16, 4);
INSERT INTO ALBUM VALUES(null, 'Dwell', 1991, 'EP', 17, 4);
INSERT INTO ALBUM VALUES(null, 'Ressurection', 1991, 'EP', 18, 4);
INSERT INTO ALBUM VALUES(null, 'My Fire Burns On', 1992, 'EP', 19, 4);
INSERT INTO ALBUM VALUES(null, 'You Won''t Be Back', 1992, 'EP', 21, 4);
INSERT INTO ALBUM VALUES(null, 'A Light In The Dark', 1992, 'LP', 3, 4);
INSERT INTO ALBUM VALUES(null, 'Bleed To Me', 1993, 'EP', 20, 4);
INSERT INTO ALBUM VALUES(null, 'Background', 1992, 'LP', 17, 4);
INSERT INTO ALBUM VALUES(null, 'Ritual', 1993, 'LP', 21, 4);

INSERT INTO ALBUM VALUES(null, 'Unseen', 1990, 'EP', 1, 5);
INSERT INTO ALBUM VALUES(null, 'Coming Of Age', 1990, 'EP', 2, 5);
INSERT INTO ALBUM VALUES(null, 'Voice Of Thousands', 1990, 'LP', 4, 5);
INSERT INTO ALBUM VALUES(null, 'Looking Out For # 1', 1990, 'LP', 5, 5);
INSERT INTO ALBUM VALUES(null, 'All This Hate', 1990, 'EP', 6, 5);
INSERT INTO ALBUM VALUES(null, 'If This Is Right', 1991, 'EP', 7, 5);
INSERT INTO ALBUM VALUES(null, 'In A Time Of Hate', 1990, 'LP', 8, 5);
INSERT INTO ALBUM VALUES(null, 'The Price Of Maturity', 1991, 'LP', 2, 5);
INSERT INTO ALBUM VALUES(null, 'World of Fire', 1992, 'LP', 9, 5);
INSERT INTO ALBUM VALUES(null, 'Hard Stance', 1993, 'EP', 10, 5);
INSERT INTO ALBUM VALUES(null, 'Face Reality', 1994, 'EP', 10, 5);
INSERT INTO ALBUM VALUES(null, 'The Current', 1994, 'EP', 3, 5);