-- MySQL Script generated by MySQL Workbench
-- 02/24/17 21:51:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `EmployeeNumber` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`EmployeeNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROJECT` (
  `ProjectID` INT NOT NULL,
  `ProjectName` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NULL,
  `MaxHours` INT(9) NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  PRIMARY KEY (`ProjectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE_has_PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE_has_PROJECT` (
  `EMPLOYEE_EmployeeNumber` INT NOT NULL,
  `PROJECT_ProjectID` INT NOT NULL,
  PRIMARY KEY (`EMPLOYEE_EmployeeNumber`, `PROJECT_ProjectID`),
  INDEX `fk_EMPLOYEE_has_PROJECT_PROJECT1_idx` (`PROJECT_ProjectID` ASC),
  INDEX `fk_EMPLOYEE_has_PROJECT_EMPLOYEE_idx` (`EMPLOYEE_EmployeeNumber` ASC),
  CONSTRAINT `fk_EMPLOYEE_has_PROJECT_EMPLOYEE`
    FOREIGN KEY (`EMPLOYEE_EmployeeNumber`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_has_PROJECT_PROJECT1`
    FOREIGN KEY (`PROJECT_ProjectID`)
    REFERENCES `mydb`.`PROJECT` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
